DROP SEQUENCE MEMBER_SEQUENCE;
DROP SEQUENCE REVIEW_SEQUENCE;

DROP TABLE REVIEW;
DROP TABLE MEMBER;


CREATE TABLE REVIEW 
( NUM NUMBER(20) NOT NULL
, NAME VARCHAR2(20 BYTE) NOT NULL
, PASSWORD VARCHAR2(20 BYTE) NOT NULL
, CONTENT VARCHAR2(100 BYTE) NOT NULL 
, HEART NUMBER(20) DEFAULT 0 
, CONSTRAINT REVIEW_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);
CREATE TABLE MEMBER 
( NUM NUMBER(20) NOT NULL
, NAME VARCHAR2(20 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) NOT NULL 
, PHONE NUMBER(20, 0) NOT NULL
, COUPONT VARCHAR2(20 BYTE) NOT NULL
, CONSTRAINT MEMBER_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE
);
--SEQUENCE 持失
CREATE SEQUENCE MEMBER_SEQUENCE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE REVIEW_SEQUENCE INCREMENT BY 1 START WITH 1 MINVALUE 1;
--TRIGGER 持失
CREATE TRIGGER MEMBER_TRG 
BEFORE INSERT ON MEMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NUM IS NULL THEN
      SELECT MEMBER_SEQUENCE.NEXTVAL INTO :NEW.NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
CREATE TRIGGER REVIEW_TRG 
BEFORE INSERT ON REVIEW 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NUM IS NULL THEN
      SELECT REVIEW_SEQUENCE.NEXTVAL INTO :NEW.NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
--VIEW 持失
CREATE VIEW REVIEW_MODIFY_VIEW
AS SELECT NUM, CONTENT
FROM REVIEW;

CREATE VIEW REVIEW_HEART_VIEW
AS SELECT NUM, HEART
FROM REVIEW;

--INDEX 持失
CREATE INDEX REVIEW_INDEX ON REVIEW (NUM DESC);



